numbers: [3,1,4,5,2]
people:
  - name: Dave
    age: 22
    
  - name: Bob
    age: 20
    
  - name: Mark
    age: 17
    
  - name: Alex
    age: 21
    
  - name: Chris
    age: 19

jekyll_sort:
  - src: numbers
    direction: up
    dest: numbers_sorted
    
  - src: people
    by: name
    direction: up
    dest: people_sorted_by_name
    
  - src: people
    by: age
    direction: down
    dest: people_sorted_by_age_desc
    
  - src: posts
    by: title
    direction: down
    dest: posts_sorted_by_title_desc
    
  - src: posts
    by: date
    direction: down
    dest: posts_sorted_by_date_desc
    
  - src: posts
    by: category
    direction: up
    dest: posts_sorted_by_category
    
  - src: posts
    by: order
    direction: up
    dest: posts_sorted_by_order